---
title: "PSYC 245 Exam Formulas"
subtitle: "(scroll down for the exam you need)"
author: "Patrick Bolger, PhD"
date: "29 April 2021"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
output: 
  rmdformats::downcute:
    use_bookdown: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# PSYC 245

## Exam 2

### The Interquartile Range (*IQR*)

$$Q_3-Q_1$$
<br/>

### The mean

$$\overline{x}=\frac{\sum{x_i}}{n}$$
<br/>

### The variance


$$s^2=\frac{\sum(x_i-\overline{x})^2}{n-1}$$

<br/>

### the standard deviation

$$s=\sqrt{\frac{\sum(x_i-\overline{x})^2}{n-1}}$$
<br/>

### the *z*-score


$$z_i=\frac{x_i-\overline{x}}{s}$$

<br/>

### a raw score, given a z-score, an SD, and a mean

$$x_i=z_i(s)+\overline{x}$$

<br/>

### Pearson's *r* correlation coefficient

$$r_{x,y}=\frac{\sum z_{(x_i)}z_{(y_i)}}{n-1}$$

<br/>

### Simple Regression equation

$$y=a+bX$$

## Exam 3

### Odds

$$Odds = A\ to\ B$$

### probability from odds

$$\frac{B}{A+B}$$

### expected value

$$Expected\ value=a_1p_1+a_2p_2+\ ...a_kp_k$$

, where

*a*: possible outcomes  
*p*: associated probabilities  
*k*: number of possible outcomes  

---

<br/>

## Exam 4

### **Rough** 95% Confidence Interval for a proportion

$$95\%\ CI_p= \hat{p}\pm\Bigg(2\times\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\Bigg)$$
<br/>

### **More exact** Confidence Intervals for a proportion

$$CI_p= \hat{p}\pm\Bigg(z^*\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\Bigg)$$
<br/>

### Important $z^*$ values

- 95th percentile  
  - 1.64  
<br/>
- Middle 95% of normal curve  
  - [-1.96, +1.96]
- 97.5th percentile  
  - 1.96  
- 2.5th percentile  
  - -1.96  
<br/>
- Middle 99% of normal curve  
  - [-2.58, +2.58]  
- 99.5th percentile  
  - 2.58  
- 0.5th percentile  
  - -2.58  
<br/>
(for more, see [http://www.normaltable.com/](http://www.normaltable.com/))
  
<br/>

### Confidence Intervals for a mean

$$95\%\ CI_{\mu}= \bar{x}\pm\Bigg(z^*\times\frac{s}{\sqrt{n}}\Bigg)$$
<br/>

### *p*-value

$$p=P\big(D|H_0\big)$$
<br/>

### Test statistics

<br/>

---

#### *z*-test for a proportion

$$z=\frac{\hat{p}-p_{null}}{SE_{\hat{p}}}$$
<br/>

[the sample proportion ($\hat{p}$) minus the proportion assumed under the null hypothesis ($p_{null}$), divided by the standard error of the proportion ($SE_{\hat{p}}$)]

<br/>

##### standard error for a proportion

$$SE_{\hat{p}}=\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}$$
<br/>

##### Combined formula for a *z*-test for a proportion

$$z=\frac{\hat{p}-p_{null}}{\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}}$$

---

#### *z*-test for a mean

$$z=\frac{\bar{x}-\mu_{null}}{SE_{mean}}$$
<br/>

[the sample mean ($\bar{x}$) minus the mean assumed under the null hypothesis ($\mu_{null}$), divided by the standard error of the mean ($SE_{mean}$)]

<br/>

##### The standard error of the mean

$$SE_{mean}=\frac{s}{\sqrt{n}}$$
<br/>

##### Combined formula for a *z*-test of a mean

$$z=\frac{\bar{x}-\mu_{null}}{s \big/\sqrt{n}}$$